export const CATEGORIES={
'Alltag':{youth:['Kühlschrank','Zahnbürste','Regenschirm','Rucksack','Kopfhörer','Schlüssel','Kaffeemaschine','Staubsauger','Sofa','Wecker','Spiegel','Kerze','Handtuch','Fahrrad','Fernbedienung','Waschmaschine','Mikrowelle','Ladekabel','Balkon','Briefkasten'],adult:['Katerfrühstück','Steuererklärung','Überstunden','Dispo','Wohnungsbesichtigung','Gehaltsverhandlung']},
'Essen & Trinken':{youth:['Pizza','Sushi','Spaghetti','Taco','Croissant','Lasagne','Pfannkuchen','Döner','Popcorn','Eiscreme','Käsekuchen','Brezel','Pommes','Müsli','Burger','Ramen','Waffel','Smoothie','Nachos','Gummibärchen'],adult:['Espresso Martini','Aperol Spritz','Tequila','Craft Beer','Weinprobe','Katerfrühstück']},
'Orte':{youth:['Flughafen','Strand','Supermarkt','Kino','Schule','Bahnhof','Museum','Campingplatz','Bäckerei','Stadion','Bibliothek','Schwimmbad','Restaurant','Berg','Zoo','Freizeitpark','Eisdiele','Turnhalle','Hotel','Spielplatz'],adult:['Nachtclub','Cocktailbar','Weinbar','Junggesellenabschied','Casino','Afterparty']},
'Tiere':{youth:['Pinguin','Elefant','Känguru','Delfin','Giraffe','Eichhörnchen','Oktopus','Flamingo','Waschbär','Krokodil','Koala','Papagei','Igel','Panda','Seehund','Alpaka','Axolotl','Faultier','Erdmännchen','Otter'],adult:[]},
'Freizeit & Sport':{youth:['Fußball','Gaming','Wandern','Kochen','Fotografie','Schwimmen','Karaoke','Bowling','Yoga','Tanzen','Lesen','Gärtnern','Skifahren','Surfen','Angeln','Basketball','Bouldern','Tischtennis','Skateboard','Escape Room'],adult:['Pubquiz','Weinprobe','Festivalcamping','Pokerabend','Barhopping','Afterwork']},
'Medien & Kultur':{youth:['Superheld','Podcast','Kinofilm','Manga','Streaming','Brettspiel','Roman','Graffiti','Musical','Zauberer','Detektiv','Influencer','Memes','Science-Fiction','Fantasy','Dokumentation','Hörbuch','Konzert','Theater','Comic'],adult:['True Crime','Dating-Show','Late-Night-Show','Reality-TV','Stand-up-Comedy']},
'Reisen':{youth:['Koffer','Reisepass','Zelt','Jugendherberge','Landkarte','Souvenir','Sonnencreme','Wanderweg','Fähre','Wohnmobil','Insel','Wasserfall','Skigebiet','Altstadt','Aussichtspunkt','Rundreise','Städtetrip','Raststätte','Seilbahn','Ferienhaus'],adult:['All-inclusive','Wellnesshotel','Minibar','Geschäftsreise','Mietwagen','Flitterwochen']},
'Beziehungen & Party':{youth:['Freundschaft','Geburtstag','Überraschungsparty','Tanzfläche','Selfie','Geschenk','Gruppenchat','Playlist','Pyjamaparty','Kompliment'],adult:['Blind Date','Tinder','Flirt','One-Night-Stand','Ex-Partner','Speed-Dating','Kuss','Affäre','Hangover','Clubnacht','Junggesellenabschied','Dating-App','Schwiegermutter','Hochzeitsnacht','Beziehungsstatus']}
};
export const VARIANTS={classic:{name:'Klassisch',description:'Der Imposter kennt das geheime Wort nicht.',hint:false},hint:{name:'Mit Hinweis',description:'Der Imposter bekommt die Kategorie als Hinweis.',hint:true},chaos:{name:'Chaos',description:'Mehr Imposter empfohlen – ideal für größere Gruppen.',hint:false},quick:{name:'Blitzrunde',description:'Kurze 2-Minuten-Diskussion für schnelle Runden.',hint:false}};
export function wordsFor(category='Zufall',audience='youth',custom=[]){if(category==='Eigene Wörter')return custom;const keys=category==='Zufall'?Object.keys(CATEGORIES):[category];return keys.flatMap(k=>{const c=CATEGORIES[k];return c?[...c.youth,...(audience==='adult'?c.adult:[])]:[]}).filter(Boolean)}
export function clampImposters(count,players){return Math.max(1,Math.min(Number(count)||1,Math.max(1,players-2)))}
export function pickRound(players,category='Zufall',imposterCount=1,customWords=[],audience='youth',variant='classic'){if(players.length<3)throw new Error('Mindestens 3 Spieler benötigt.');const names=players.map(p=>typeof p==='string'?p:p.name),words=wordsFor(category,audience,customWords).map(String).map(w=>w.trim()).filter(Boolean);if(!words.length)throw new Error('Keine Wörter in dieser Kategorie.');const word=words[Math.floor(Math.random()*words.length)],n=clampImposters(imposterCount,names.length),ids=[...names.keys()];for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}const imposters=new Set(ids.slice(0,n));return{word,category,variant,roles:names.map((name,i)=>({name,imposter:imposters.has(i)}))}}
export function tallyVotes(votes){const counts={};Object.values(votes).forEach(id=>{if(id)counts[id]=(counts[id]||0)+1});const max=Math.max(0,...Object.values(counts));return{counts,winners:Object.keys(counts).filter(k=>counts[k]===max&&max>0)}}