<?php
declare(strict_types=1);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function out($v,$s=200){http_response_code($s);echo json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function body(){return json_decode(file_get_contents('php://input'),true)?:[];} function tok(){return bin2hex(random_bytes(18));}
function code(){ $a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';$s='';for($i=0;$i<5;$i++)$s.=$a[random_int(0,strlen($a)-1)];return $s;}
function db(){static $d=null;if($d)return $d;$dir=__DIR__.'/../data';if(!is_dir($dir))mkdir($dir,0770,true);$d=new PDO('sqlite:'.$dir.'/imposter.sqlite');$d->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$d->exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS rooms(code TEXT PRIMARY KEY,host_token TEXT NOT NULL,state TEXT NOT NULL,updated INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY,room TEXT NOT NULL,name TEXT NOT NULL,token TEXT UNIQUE NOT NULL,role TEXT,word TEXT,last_seen INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS votes(room TEXT NOT NULL,voter TEXT NOT NULL,target TEXT NOT NULL,PRIMARY KEY(room,voter));');return $d;}
function room($c){$q=db()->prepare('SELECT * FROM rooms WHERE code=?');$q->execute([$c]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new Exception('Raum nicht gefunden.');$r['state']=json_decode($r['state'],true);return $r;}
function players($c){$q=db()->prepare('SELECT id,name,last_seen FROM players WHERE room=? ORDER BY rowid');$q->execute([$c]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function auth($c,$t){$q=db()->prepare('SELECT * FROM players WHERE room=? AND token=?');$q->execute([$c,$t]);$p=$q->fetch(PDO::FETCH_ASSOC);if(!$p)throw new Exception('Sitzung ungültig.');db()->prepare('UPDATE players SET last_seen=? WHERE id=?')->execute([time(),$p['id']]);return $p;}
function saveRoom($c,$s){db()->prepare('UPDATE rooms SET state=?,updated=? WHERE code=?')->execute([json_encode($s,JSON_UNESCAPED_UNICODE),time(),$c]);}
function view($r,$p){$s=$r['state'];$ps=players($r['code']);$v=['code'=>$r['code'],'phase'=>$s['phase'],'settings'=>$s['settings'],'players'=>array_map(fn($x)=>['id'=>$x['id'],'name'=>$x['name'],'connected'=>$x['last_seen']>time()-8],$ps),'me'=>['id'=>$p['id'],'name'=>$p['name'],'isHost'=>hash_equals($r['host_token'],$p['token'])]];if(in_array($s['phase'],['game','vote']))$v['role']=['imposter'=>$p['role']==='imposter','word'=>$p['word'],'knowsImposter'=>$p['role']==='imposter'&&$s['settings']['variant']==='open'];if($s['phase']==='result'){$q=db()->prepare('SELECT target,COUNT(*) n FROM votes WHERE room=? GROUP BY target');$q->execute([$r['code']]);$votes=[];foreach($q as $x)$votes[$x['target']]=(int)$x['n'];$q=db()->prepare("SELECT id FROM players WHERE room=? AND role='imposter'");$q->execute([$r['code']]);$v['result']=['word'=>$s['word'],'imposterWord'=>$s['imposterWord']??null,'imposters'=>$q->fetchAll(PDO::FETCH_COLUMN),'votes'=>$votes];}return $v;}
function wordPools(){return require __DIR__.'/words.php';}
try{$d=body();$action=$_GET['action']??'state';$pdo=db();$pdo->prepare('DELETE FROM rooms WHERE updated<?')->execute([time()-21600]);$pdo->exec("DELETE FROM players WHERE room NOT IN (SELECT code FROM rooms); DELETE FROM votes WHERE room NOT IN (SELECT code FROM rooms)");
if($action==='create'){$name=trim(substr((string)($d['name']??''),0,24));if(!$name)throw new Exception('Bitte Namen eingeben.');do{$c=code();$q=$pdo->prepare('SELECT 1 FROM rooms WHERE code=?');$q->execute([$c]);}while($q->fetch());$t=tok();$s=['phase'=>'lobby','settings'=>['category'=>'Zufall','profile'=>'mixed','variant'=>'open','imposters'=>1,'minutes'=>5,'customWords'=>[]],'word'=>null];$pdo->prepare('INSERT INTO rooms VALUES(?,?,?,?)')->execute([$c,$t,json_encode($s),time()]);$pdo->prepare('INSERT INTO players VALUES(?,?,?,?,?,?,?)')->execute([tok(),$c,$name,$t,null,null,time()]);out(['code'=>$c,'token'=>$t]);}
$c=strtoupper((string)($d['code']??$_GET['code']??''));if($action==='join'){$r=room($c);if($r['state']['phase']!=='lobby')throw new Exception('Die Runde läuft bereits.');$name=trim(substr((string)($d['name']??''),0,24));if(!$name)throw new Exception('Bitte Namen eingeben.');$q=$pdo->prepare('SELECT COUNT(*) FROM players WHERE room=?');$q->execute([$c]);if($q->fetchColumn()>=12)throw new Exception('Raum ist voll.');$q=$pdo->prepare('SELECT COUNT(*) FROM players WHERE room=? AND lower(name)=lower(?)');$q->execute([$c,$name]);if($q->fetchColumn())throw new Exception('Name bereits vergeben.');$t=tok();$pdo->prepare('INSERT INTO players VALUES(?,?,?,?,?,?,?)')->execute([tok(),$c,$name,$t,null,null,time()]);out(['code'=>$c,'token'=>$t]);}
$t=(string)($d['token']??$_GET['token']??'');$r=room($c);$p=auth($c,$t);$host=hash_equals($r['host_token'],$t);
if($action==='settings'){if(!$host||$r['state']['phase']!=='lobby')throw new Exception('Nur der Host kann Einstellungen ändern.');$allowed=['category','profile','variant','imposters','minutes','customWords'];foreach(($d['settings']??[]) as $k=>$v)if(in_array($k,$allowed,true))$r['state']['settings'][$k]=$v;$r['state']['settings']['imposters']=max(1,min(3,(int)$r['state']['settings']['imposters']));$r['state']['settings']['minutes']=max(1,min(20,(int)$r['state']['settings']['minutes']));saveRoom($c,$r['state']);}
elseif($action==='start'){if(!$host)throw new Exception('Nur der Host kann starten.');$ps=players($c);if(count($ps)<3)throw new Exception('Mindestens 3 Spieler benötigt.');$s=$r['state']['settings'];$pools=wordPools();$pairs=[];if($s['category']==='Eigene Wörter'){foreach(($s['customWords']??[]) as $line){$x=array_map('trim',explode('|',(string)$line,2));if($x[0]??null)$pairs[]=['a'=>$x[0],'b'=>$x[1]??null,'category'=>'Eigene Wörter'];}}else{foreach($pools as $cat=>$items)if($s['category']==='Zufall'||$s['category']===$cat)foreach($items as $x)if(in_array('all',$x['profiles'],true)||($s['profile']!=='mixed'&&in_array($s['profile'],$x['profiles'],true)))$pairs[]=['a'=>$x['a'],'b'=>$x['b'],'category'=>$cat];}if(!$pairs)throw new Exception('Keine Begriffe verfügbar.');$pair=$pairs[array_rand($pairs)];if($s['variant']==='secret'&&empty($pair['b']))throw new Exception('Verdeckter Imposter benötigt Begriffspaare.');if(!empty($pair['b'])&&random_int(0,1)){$z=$pair['a'];$pair['a']=$pair['b'];$pair['b']=$z;}shuffle($ps);$n=max(1,min((int)$s['imposters'],count($ps)-2));$imp=array_flip(array_column(array_slice($ps,0,$n),'id'));foreach($ps as $x){$is=isset($imp[$x['id']]);$shown=$is?($s['variant']==='secret'?$pair['b']:null):$pair['a'];$pdo->prepare('UPDATE players SET role=?,word=? WHERE id=?')->execute([$is?'imposter':'civilian',$shown,$x['id']]);}$r['state']['word']=$pair['a'];$r['state']['imposterWord']=$pair['b'];$r['state']['roundCategory']=$pair['category'];$r['state']['phase']='game';$pdo->prepare('DELETE FROM votes WHERE room=?')->execute([$c]);saveRoom($c,$r['state']);}
elseif($action==='phase'){if(!$host)throw new Exception('Nur der Host.');$phase=$d['phase']??'';if(!in_array($phase,['vote','result','lobby'],true))throw new Exception('Ungültige Phase.');$r['state']['phase']=$phase;if($phase==='lobby'){$r['state']['word']=null;$pdo->prepare('UPDATE players SET role=NULL,word=NULL WHERE room=?')->execute([$c]);$pdo->prepare('DELETE FROM votes WHERE room=?')->execute([$c]);}saveRoom($c,$r['state']);}
elseif($action==='vote'){$r=room($c);if($r['state']['phase']!=='vote')throw new Exception('Abstimmung ist nicht aktiv.');$target=(string)($d['target']??'');$q=$pdo->prepare('SELECT 1 FROM players WHERE room=? AND id=?');$q->execute([$c,$target]);if(!$q->fetch())throw new Exception('Ungültige Stimme.');$pdo->prepare('INSERT INTO votes(room,voter,target) VALUES(?,?,?) ON CONFLICT(room,voter) DO UPDATE SET target=excluded.target')->execute([$c,$p['id'],$target]);}
$r=room($c);out(['room'=>view($r,$p)]);
}catch(Throwable $e){out(['error'=>$e->getMessage()],400);}